### ISSUE TITLE
getting parse errors with svelte latest release.

### ISSUE THREAD

**Issue by JohnRSim** [Ennoriel/svelte-awesome-color-picker#10]
Not sure what's going on..

#### Code
```
<svelte:options tag="test-comp" />

<script>
//svelte
import { onMount, tick } from "svelte";

//lib
import ColorPicker from 'svelte-awesome-color-picker';

let hex;
</script>

<ColorPicker bind:hex />
```

#### Error
```
11:48:49 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: C:/work/bitmapbytes/git/OCM-QR-Field/node_modules/svelte-awesome-color-picker/components/variant/circle-picker/Wrapper.svelte?v=2cfa38bd
  4  |  /* svelte-ignore unused-export-let */
  5  |  export let toRight;
  6  |  </script>
     |           ^
  7  |
  8  |  <div class="wrapper" bind:this={wrapper} class:isOpen class:isPopup>
      at formatError (file:///C:/work/bitmapbytes/git/OCM-QR-Field/node_modules/vite/dist/node/chunks/dep-cff57044.js:40841:46)
      at TransformContext.error (file:///C:/work/bitmapbytes/git/OCM-QR-Field/node_modules/vite/dist/node/chunks/dep-cff57044.js:40837:19)
      at TransformContext.transform (file:///C:/work/bitmapbytes/git/OCM-QR-Field/node_modules/vite/dist/node/chunks/dep-cff57044.js:37508:22)
      at async Object.transform (file:///C:/work/bitmapbytes/git/OCM-QR-Field/node_modules/vite/dist/node/chunks/dep-cff57044.js:41090:30)
      at async loadAndTransform (file:///C:/work/bitmapbytes/git/OCM-QR-Field/node_modules/vite/dist/node/chunks/dep-cff57044.js:37351:29)
```

#### Package
```

  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.0.2",
    "svelte": "^3.49.0",
    "svelte-awesome-color-picker": "^1.2.3",
    "vite": "^3.1.0"
  },
  "dependencies": {
    "dotenv": "^16.0.2",
    "svelte-preprocess": "^4.10.7"
  }
}
```

**Comment by Ennoriel** [comment]
Hi @JohnRSim !

Does this compile without svelte-awesome-color-picker? Can you link a repository?

Your example is working fine on the REPL: https://svelte.dev/repl/a4f7c341c2af48699d917a4d37c18d2a?version=3.50.1
