### ISSUE TITLE
Svelte components not found

### ISSUE THREAD

**Issue by kamiyaa** [Ennoriel/svelte-awesome-color-picker#48]
Project structure:
```
abc
  |
  [slug]
      |
      uvw
        |
        xyz
```

This error shows up when I navigate to `/adc/def/uvw/xyz`,
where I have a few `<ColorPicker />` setup.

It looks like the `ColorPicker` component is trying to import components from my own project?
Potentially, some weird interaction with local imports?
ie. `import x from '../Input.svelte'`

```sh
Error: Not found: /abc/def/uvw/ColorPicker.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/Input.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/Wrapper.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/Picker.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/PickerWrapper.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/PickerIndicator.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/Slider.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/SliderWrapper.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/SliderIndicator.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/Alpha.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /abc/def/uvw/TextInput.svelte
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:431:13)
    at resolve (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:278:5)
    at Object.#options.hooks.handle (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/index.js:56:56)
    at Module.respond (<project_directory>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Dependencies:
```json
"devDependencies": {
    ...
    "@rollup/plugin-typescript": "8.3.3",
    "@sveltejs/adapter-auto": "^1.0.0",
    "@sveltejs/adapter-node": "^1.2.0",
    "@sveltejs/kit": "^1.20.4",
    "svelte": "^4.0.5",
    "svelte-awesome-color-picker": "^2.4.6",
    "svelte-check": "^3.4.3",
    "svelte-preprocess": "^5.0.1",
    "tailwindcss": "^3.2.4",
    "tslib": "^2.4.1",
    "typescript": "^5.0.0",
    "vite": "^4.4.2",
    ...
},
"dependencies": {
    "colord": "^2.9.3",
    ...
}
```

**Comment by kamiyaa** [comment]
I think its due to some prerender, csr, ssr settings.
Changing them around fixed the issue

**Comment by Ennoriel** [comment]
Glad you solved your issue! :)
Let me know if you think there is a real issue in the repo ;)
